### PR TITLE
:rocket: Math Magicians: Tests

### PR DESCRIPTION
**Pull request by mahabubx7**
### :rocket: Math Magicians: Tests

- [x] No linters error.
- [x] Maintained `git-flow` and `GitHub workflows`.
- [x] Using `react-testing-library` for the tests.
- [x] Wrote unit tests for the files `operate.js` using Jest.
- [x] Wrote unit tests for the files `calculate.js` using Jest.
- [x] Created unit tests for all components.
- [x] Used `Jest` snapshot for testing the components.
- [x] Used React Testing Library to simulate user interaction.
- [x] Run full tests suite using Jest. All tests should pass.

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @mahabubx7, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the student's success team and they'll permit you to work solo or look for a suitable partner.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by topeogunleye** [comment]
@mahabubx7, I read your comment on your PR and will get back to you in a minute. please let me consult other code reviewers.

**Comment by topeogunleye** [comment]
@mahabubx7 I have received feedback from a senior code reviewer, and it appears that we are not allowed to review a pair programming activity without the approval from the Student Success team if the student worked alone.

Therefore, I kindly request that you contact the Student Success team to obtain approval to work alone on the project. If you receive approval, please upload a screenshot of your conversation with Student Success on the pull request so that we can proceed with the review.

Please let me know if you require any further assistance or have any questions.

Thank you,
Temitope

**Review by AnselemOdims — APPROVED** [review]
### Hi  @team🙋‍♀️, 
Good job implementing all the project requirements for this milestone/project.

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
